openapi: 3.0.3
info:
  title: API
  version: 1.0.0
servers:
  - url: http://127.0.0.1:5000/api
paths:
  /notes:
    get:
      tags:
        - note
      summary: Get all notes
      description: Get all notes
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'      
  /note/{id}:
    get:
      tags:
        - note
      summary: Get one note
      description: Get one note
      parameters:
        - name: id
          in: path
          required: true
          description: ID of pet to return
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
  /createNote:
    post:
      tags:
        - note
      summary: Create note
      description: Create note
      requestBody:
        description: Create note
        content:
          application/json:
            schema:
              properties:
                header:
                  type: string
                body:
                  type: string
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
components:
  schemas:
    Note:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        header:
          type: string
          example: "First note"
        body:
          type: string
          example: "First note"
        date:
          type: string
          format: date-time

